### PR TITLE
Api

### PR DESCRIPTION
**Pull request by AbrahaKahsay**
## Project description
In this project, a leaderboard app is created. The leaderboard website displays scores submitted by different players. It also allows you to submit your score. All data is preserved thanks to the external Leaderboard API service.

It has the objectives of using:

- Send and receive data from an API.
- Use API documentation.
- Understand and use JSON.
- Make JavaScript code asynchronous.
## Built with

- Major languages: HTML, CSS, JavaScript
- Technologies used: VS Code, Github, Linters, Firefox web-browser
- webpack
- API's

### CODE REVIEW

**Comment by AbrahaKahsay** [comment]
Dear reviewer, I couldn't understand the nature of the linter errors.

**Review by tresorsawasawa — COMMENTED** [review]
# STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @AbrahaKahsay 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request  🛑 🛑

You have submitted a project that has linters errors. Kindly make sure you fix them before requesting a new review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

---
Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

---
_Invalid Code Review Request **Does not count** into the code reviews limit._

**Review by wuletawwonte — COMMENTED** [review]
Hi @AbrahaKahsay 👋🏿👋🏿👋🏿,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a failing linter test. Please fix the linter errors before requesting a review. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready :pray:

Cheers and Happy coding!:clap::clap::clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by AbrahaKahsay** [comment]
@tresorsawasawa @wuletawwonte Thanks for the response. I will fix it. would you suggest some insight? I would appreciate that!

**Comment by wuletawwonte** [comment]
### Hi @AbrahaKahsay 
Maybe try deleting `package-lock.json` file as well as `node_modules` folder. then run `npm install` to install all packages again.

**Comment by tresorsawasawa** [comment]
Hi @AbrahaKahsay 

If the above approach doesn't work. I suggest you delete both **package.json** and **package-lock.json** files(**as I noticed that you have many dependencies from the **package.json** file**) Then restart the **Webpack** configuration from the beginning and even check the linters config if you didn't mistakenly change any file.

You can leave another comment if you didn't get the solution or even text me on slack

**Comment by AbrahaKahsay** [comment]
> Hi @AbrahaKahsay
> 
> If the above approach doesn't work. I suggest you delete both **package.json** and **package-lock.json** files(**as I noticed that you have many dependencies from the **package.json** file**) Then restart the **Webpack** configuration from the beginning and even check the linters config if you didn't mistakenly change any file.
> 
> You can leave another comment if you didn't get the solution or even text me on slack

**Comment by AbrahaKahsay** [comment]
Hi @tresorsawasawa @wuletawwonte , your suggestions were valuable. I completely reinstalled the webpack and it worked. thanks!

**Review by Ghiftee — APPROVED** [review]
## STATUS: APPROVED ♻️♻️
Hi @AbrahaKahsay, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

**Pull request merged**
